# Generated by Django 3.2.6 on 2021-08-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
